name: "Mirror doc/ to wiki"
on:
  push:
    branches:
      - master
    paths:
      - 'doc/**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          path: wiki-mirror
      - name: Checkout wiki
        uses: actions/checkout@v2
        with:
          repository: "Smittyvb/wiki-mirror.wiki"
          path: wiki-mirror.wiki
      - name: Copy files
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Wiki mirror"
          cp $GITHUB_WORKSPACE/wiki-mirror/doc/*.txt $GITHUB_WORKSPACE/wiki-mirror.wiki
          cd $GITHUB_WORKSPACE/wiki-mirror.wiki
          rename.ul -v .txt .md *.txt
          git add .
          # only commit if there are changes
          git diff-index --quiet HEAD -- || git commit "sync from doc/"
          git push
